### ISSUE TITLE
Страница предмета

### ISSUE THREAD

**Issue by jFoxSingularity** [jFoxSingularity/ReflectHero#3]
Нужна страница с описанием предмета.

**Comment by jFoxSingularity** [comment]
Пример (хоть и не очень удачный) можно взять со страницы описания монстра.

Удачи @vk26 :stuck_out_tongue_winking_eye: :

**Comment by vk26** [comment]
создал экшен и вьюшку.

**Comment by jFoxSingularity** [comment]
А как попасть на страницу предмета?)

**Comment by vk26** [comment]
добавил на главной странице ссылки на просмотр итемов.
